#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${DRL_BASE}/RunFunctions        # run functions
#------------------------------------------------------------------------------
# execute flow solver
runParallel $(getApplication)
# -----------------------------------------------------------------------------
