#!/bin/bash
#SBATCH --partition=standard
#SBATCH --nodes=1
#SBATCH --time=48:00:00
#SBATCH --job-name=drl_train
#SBATCH --ntasks-per-node=1

module load python/3.8.2

# adjust path if necessary
source ~/drlfoam/pydrl/bin/activate
source ~/drlfoam/setup-env --container

# start a training with a buffer size of 8 and 8 runners;
# save output to log.test_training
python3 run_training.py -o "e100_r8_b8_f0.6_sampling_startTime" -e slurm -b 8 -r 8 -f 0.6 -i 100 -m 0 -s "cylinder2D" &> log.training

# run a training with the weirOverflow case
# python3 run_training.py -o "e100_r8_b8_f70_1st_test" -e slurm -b 8 -r 8 -f 70 -i 100 -m 0 -s "weirOverflow" &> log.training


